apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: winit
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  PORT: "3000"
  HOST: "0.0.0.0"
  NODE_ENV: production
  PROMETHEUS_URL: "http://prometheus-operated.monitoring.svc.cluster.local:9090"

